
package com.mybank.ATM;

import com.mybank.domain.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;


public class myBankATM extends javax.swing.JFrame {

//    Bank bank;
    Customer currentCustomer;
    Account currentAccount;

    /**
     * Creates new form myBankATM
     */
    public myBankATM() {

//        bank = Bank.getBank();
        Customer firstCustomer = new Customer("John", "Doe");
        Customer secondCustomer = new Customer("Kulo", "Holo");

        SavingsAccount johnSavings = new SavingsAccount(1000, 10);
        CheckingAccount johnAccount = new CheckingAccount(5000, 1000);
        CheckingAccount kuloAccount = new CheckingAccount(500, 100);

        firstCustomer.addAccount(johnSavings);
        firstCustomer.addAccount(johnAccount);
        secondCustomer.addAccount(kuloAccount);

        Bank.addCustomer(firstCustomer);
        Bank.addCustomer(secondCustomer);

        this.setLocationRelativeTo(null);

        initComponents();

        for (Component c : jPanel3.getComponents()) {
            if ((c.getClass() == JButton.class) && (((JButton) c).getText() != "ENTER")) {
                JButton currentButton = (JButton) c;
                currentButton.addActionListener((ActionEvent e) -> {
                    addDigit(e);
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        checkBallanceBtn = new javax.swing.JButton();
        makeDepositBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        amountField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historyArea = new javax.swing.JTextArea();
        statusField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("my BankATM");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 350));
        setSize(new java.awt.Dimension(1200, 350));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        checkBallanceBtn.setText("Check Account Ballance");
        checkBallanceBtn.setEnabled(false);
        checkBallanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBallanceBtnActionPerformed(evt);
            }
        });
        jPanel2.add(checkBallanceBtn);

        makeDepositBtn.setText("Make a deposit");
        makeDepositBtn.setEnabled(false);
        makeDepositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeDepositBtnActionPerformed(evt);
            }
        });
        jPanel2.add(makeDepositBtn);

        withdrawBtn.setText("Make a withdraw");
        withdrawBtn.setEnabled(false);
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });
        jPanel2.add(withdrawBtn);
        jPanel2.add(amountField);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 3));

        oneButton.setText("1");
        jPanel3.add(oneButton);

        twoButton.setText("2");
        jPanel3.add(twoButton);

        threeButton.setText("3");
        jPanel3.add(threeButton);

        fourButton.setText("4");
        jPanel3.add(fourButton);

        fiveButton.setText("5");
        jPanel3.add(fiveButton);

        sixButton.setText("6");
        jPanel3.add(sixButton);

        sevenButton.setText("7");
        jPanel3.add(sevenButton);

        eightButton.setText("8");
        jPanel3.add(eightButton);

        nineButton.setText("9");
        jPanel3.add(nineButton);

        pointButton.setText(".");
        jPanel3.add(pointButton);

        zeroButton.setText("0");
        jPanel3.add(zeroButton);

        enterButton.setText("ENTER");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        jPanel3.add(enterButton);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        historyArea.setEditable(false);
        historyArea.setColumns(20);
        historyArea.setRows(5);
        jScrollPane1.setViewportView(historyArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        statusField.setEditable(false);
        statusField.setText("Welcome to myBank! <<<Enter the client ID and pressENTER...>>>");
        getContentPane().add(statusField, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBallanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBallanceBtnActionPerformed

        String accType = null;
        String protectOrInterest = null;
        if (currentAccount instanceof CheckingAccount) {
            accType = "Checking Account";
            protectOrInterest = " with overdraft protection $" + ((CheckingAccount) currentAccount).getOverdraftAmount() + "\n";
        } else {
            accType = "Savings Account";
            protectOrInterest = " with interest rate " + ((SavingsAccount) currentAccount).getInterestRate() + "%\n";
        }
        historyArea.append(String.format("Ballance of " + currentCustomer.getLastName() + " " + currentCustomer.getFirstName() + ": %s  $" + currentAccount.getBalance() + " %s", accType, protectOrInterest));
        statusField.setText("Ready...");
    }//GEN-LAST:event_checkBallanceBtnActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        int customerID = 0;
        try {
            customerID = Integer.parseInt(amountField.getText());
            currentCustomer = Bank.getCustomer(customerID);
            currentAccount = currentCustomer.getAccount(0);
            historyArea.append("Customer with ID = " + customerID + " is " + currentCustomer.getFirstName() + " " + currentCustomer.getLastName() + "\n");
            checkBallanceBtn.setEnabled(true);
            makeDepositBtn.setEnabled(true);
            withdrawBtn.setEnabled(true);
            enterButton.setEnabled(false);
            statusField.setText("Customer: " + currentCustomer.getLastName() + " " + currentCustomer.getFirstName());
        } catch (Exception e) {
            historyArea.append("ERROR: Customer not found or wrong Customer ID!\n");
            statusField.setText("ERROR");
        }
        amountField.setText("");
    }//GEN-LAST:event_enterButtonActionPerformed

    private void makeDepositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeDepositBtnActionPerformed
        try {
            double amt = Double.parseDouble(amountField.getText());
            currentAccount.deposit(amt);
            historyArea.append("Deposit: $" + amt + ", new balance is $" + currentAccount.getBalance() + "\n");
            statusField.setText("Ready...");
        } catch (Exception e) {
            historyArea.append("ERROR: Can't complete deposit operation\n");
            statusField.setText("ERROR");
        }
        amountField.setText("");
    }//GEN-LAST:event_makeDepositBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        try {
            double amt = Double.parseDouble(amountField.getText());
            currentAccount.withdraw(amt);
            historyArea.append("Withdraw: $" + amt + ", new balance is $" + currentAccount.getBalance() + "\n");
            statusField.setText("Ready...");
        } catch (OverdraftException oe) {
            historyArea.append("Sorry, Insufficient funds! Deficit is -$" + oe.getDeficit() + "\n");
        } catch (Exception e) {
            historyArea.append("ERROR: Can't complete deposit operation\n");
            statusField.setText("ERROR");
        }
        amountField.setText("");
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void addDigit(ActionEvent evt) {
        amountField.setText(amountField.getText() + ((JButton) evt.getSource()).getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myBankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myBankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myBankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myBankATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myBankATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JButton checkBallanceBtn;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JTextArea historyArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeDepositBtn;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JTextField statusField;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
